services:
  backend:
    build:
      context: ./backend
    container_name: auth_server_backend
    ports:
      - "127.0.0.1:8082:8082"
    restart: always
    networks:
      - toolhub-net
    depends_on:
      - dozzle

  frontend:
    build:
      context: ./frontend/toolhub-login
    container_name: auth_server_frontend
    ports:
      - "127.0.0.1:3003:3003"
    restart: always
    networks:
      - toolhub-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    # Optional: keep host access if you want
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
    networks:
      - toolhub-net

networks:
  toolhub-net:
    driver: bridge
