services:
  backend:
    build:
      context: ./backend
    container_name: auth_server_backend
    ports:
      - "127.0.0.1:8082:8082"
    restart: always
    networks:
      - toolhub-net

  frontend:
    build:
      context: ./frontend/toolhub-login
    container_name: auth_server_frontend
    ports:
      - "3003:3003"
    restart: always
    networks:
      - toolhub-net

networks:
  toolhub-net:
    driver: bridge
